# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /tmp/tauchain

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /tmp/tauchain

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /tmp/tauchain/CMakeFiles /tmp/tauchain/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /tmp/tauchain/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tau

# Build rule for target.
tau: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tau
.PHONY : tau

# fast build rule for target.
tau/fast:
	$(MAKE) -f CMakeFiles/tau.dir/build.make CMakeFiles/tau.dir/build
.PHONY : tau/fast

cli.o: cli.cpp.o
.PHONY : cli.o

# target to build an object file
cli.cpp.o:
	$(MAKE) -f CMakeFiles/tau.dir/build.make CMakeFiles/tau.dir/cli.cpp.o
.PHONY : cli.cpp.o

cli.i: cli.cpp.i
.PHONY : cli.i

# target to preprocess a source file
cli.cpp.i:
	$(MAKE) -f CMakeFiles/tau.dir/build.make CMakeFiles/tau.dir/cli.cpp.i
.PHONY : cli.cpp.i

cli.s: cli.cpp.s
.PHONY : cli.s

# target to generate assembly for a file
cli.cpp.s:
	$(MAKE) -f CMakeFiles/tau.dir/build.make CMakeFiles/tau.dir/cli.cpp.s
.PHONY : cli.cpp.s

json_object.o: json_object.cpp.o
.PHONY : json_object.o

# target to build an object file
json_object.cpp.o:
	$(MAKE) -f CMakeFiles/tau.dir/build.make CMakeFiles/tau.dir/json_object.cpp.o
.PHONY : json_object.cpp.o

json_object.i: json_object.cpp.i
.PHONY : json_object.i

# target to preprocess a source file
json_object.cpp.i:
	$(MAKE) -f CMakeFiles/tau.dir/build.make CMakeFiles/tau.dir/json_object.cpp.i
.PHONY : json_object.cpp.i

json_object.s: json_object.cpp.s
.PHONY : json_object.s

# target to generate assembly for a file
json_object.cpp.s:
	$(MAKE) -f CMakeFiles/tau.dir/build.make CMakeFiles/tau.dir/json_object.cpp.s
.PHONY : json_object.cpp.s

jsonld.o: jsonld.cpp.o
.PHONY : jsonld.o

# target to build an object file
jsonld.cpp.o:
	$(MAKE) -f CMakeFiles/tau.dir/build.make CMakeFiles/tau.dir/jsonld.cpp.o
.PHONY : jsonld.cpp.o

jsonld.i: jsonld.cpp.i
.PHONY : jsonld.i

# target to preprocess a source file
jsonld.cpp.i:
	$(MAKE) -f CMakeFiles/tau.dir/build.make CMakeFiles/tau.dir/jsonld.cpp.i
.PHONY : jsonld.cpp.i

jsonld.s: jsonld.cpp.s
.PHONY : jsonld.s

# target to generate assembly for a file
jsonld.cpp.s:
	$(MAKE) -f CMakeFiles/tau.dir/build.make CMakeFiles/tau.dir/jsonld.cpp.s
.PHONY : jsonld.cpp.s

misc.o: misc.cpp.o
.PHONY : misc.o

# target to build an object file
misc.cpp.o:
	$(MAKE) -f CMakeFiles/tau.dir/build.make CMakeFiles/tau.dir/misc.cpp.o
.PHONY : misc.cpp.o

misc.i: misc.cpp.i
.PHONY : misc.i

# target to preprocess a source file
misc.cpp.i:
	$(MAKE) -f CMakeFiles/tau.dir/build.make CMakeFiles/tau.dir/misc.cpp.i
.PHONY : misc.cpp.i

misc.s: misc.cpp.s
.PHONY : misc.s

# target to generate assembly for a file
misc.cpp.s:
	$(MAKE) -f CMakeFiles/tau.dir/build.make CMakeFiles/tau.dir/misc.cpp.s
.PHONY : misc.cpp.s

nquads.o: nquads.cpp.o
.PHONY : nquads.o

# target to build an object file
nquads.cpp.o:
	$(MAKE) -f CMakeFiles/tau.dir/build.make CMakeFiles/tau.dir/nquads.cpp.o
.PHONY : nquads.cpp.o

nquads.i: nquads.cpp.i
.PHONY : nquads.i

# target to preprocess a source file
nquads.cpp.i:
	$(MAKE) -f CMakeFiles/tau.dir/build.make CMakeFiles/tau.dir/nquads.cpp.i
.PHONY : nquads.cpp.i

nquads.s: nquads.cpp.s
.PHONY : nquads.s

# target to generate assembly for a file
nquads.cpp.s:
	$(MAKE) -f CMakeFiles/tau.dir/build.make CMakeFiles/tau.dir/nquads.cpp.s
.PHONY : nquads.cpp.s

prover.o: prover.cpp.o
.PHONY : prover.o

# target to build an object file
prover.cpp.o:
	$(MAKE) -f CMakeFiles/tau.dir/build.make CMakeFiles/tau.dir/prover.cpp.o
.PHONY : prover.cpp.o

prover.i: prover.cpp.i
.PHONY : prover.i

# target to preprocess a source file
prover.cpp.i:
	$(MAKE) -f CMakeFiles/tau.dir/build.make CMakeFiles/tau.dir/prover.cpp.i
.PHONY : prover.cpp.i

prover.s: prover.cpp.s
.PHONY : prover.s

# target to generate assembly for a file
prover.cpp.s:
	$(MAKE) -f CMakeFiles/tau.dir/build.make CMakeFiles/tau.dir/prover.cpp.s
.PHONY : prover.cpp.s

rdf.o: rdf.cpp.o
.PHONY : rdf.o

# target to build an object file
rdf.cpp.o:
	$(MAKE) -f CMakeFiles/tau.dir/build.make CMakeFiles/tau.dir/rdf.cpp.o
.PHONY : rdf.cpp.o

rdf.i: rdf.cpp.i
.PHONY : rdf.i

# target to preprocess a source file
rdf.cpp.i:
	$(MAKE) -f CMakeFiles/tau.dir/build.make CMakeFiles/tau.dir/rdf.cpp.i
.PHONY : rdf.cpp.i

rdf.s: rdf.cpp.s
.PHONY : rdf.s

# target to generate assembly for a file
rdf.cpp.s:
	$(MAKE) -f CMakeFiles/tau.dir/build.make CMakeFiles/tau.dir/rdf.cpp.s
.PHONY : rdf.cpp.s

tau.o: tau.cpp.o
.PHONY : tau.o

# target to build an object file
tau.cpp.o:
	$(MAKE) -f CMakeFiles/tau.dir/build.make CMakeFiles/tau.dir/tau.cpp.o
.PHONY : tau.cpp.o

tau.i: tau.cpp.i
.PHONY : tau.i

# target to preprocess a source file
tau.cpp.i:
	$(MAKE) -f CMakeFiles/tau.dir/build.make CMakeFiles/tau.dir/tau.cpp.i
.PHONY : tau.cpp.i

tau.s: tau.cpp.s
.PHONY : tau.s

# target to generate assembly for a file
tau.cpp.s:
	$(MAKE) -f CMakeFiles/tau.dir/build.make CMakeFiles/tau.dir/tau.cpp.s
.PHONY : tau.cpp.s

unifiers.o: unifiers.cpp.o
.PHONY : unifiers.o

# target to build an object file
unifiers.cpp.o:
	$(MAKE) -f CMakeFiles/tau.dir/build.make CMakeFiles/tau.dir/unifiers.cpp.o
.PHONY : unifiers.cpp.o

unifiers.i: unifiers.cpp.i
.PHONY : unifiers.i

# target to preprocess a source file
unifiers.cpp.i:
	$(MAKE) -f CMakeFiles/tau.dir/build.make CMakeFiles/tau.dir/unifiers.cpp.i
.PHONY : unifiers.cpp.i

unifiers.s: unifiers.cpp.s
.PHONY : unifiers.s

# target to generate assembly for a file
unifiers.cpp.s:
	$(MAKE) -f CMakeFiles/tau.dir/build.make CMakeFiles/tau.dir/unifiers.cpp.s
.PHONY : unifiers.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... tau"
	@echo "... cli.o"
	@echo "... cli.i"
	@echo "... cli.s"
	@echo "... json_object.o"
	@echo "... json_object.i"
	@echo "... json_object.s"
	@echo "... jsonld.o"
	@echo "... jsonld.i"
	@echo "... jsonld.s"
	@echo "... misc.o"
	@echo "... misc.i"
	@echo "... misc.s"
	@echo "... nquads.o"
	@echo "... nquads.i"
	@echo "... nquads.s"
	@echo "... prover.o"
	@echo "... prover.i"
	@echo "... prover.s"
	@echo "... rdf.o"
	@echo "... rdf.i"
	@echo "... rdf.s"
	@echo "... tau.o"
	@echo "... tau.i"
	@echo "... tau.s"
	@echo "... unifiers.o"
	@echo "... unifiers.i"
	@echo "... unifiers.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

