#!/usr/bin/env python
import sys, os

out = ""

todo = open("todo", "r")

for line in todo:
	if line != "----\n":
		out += line
	else: # we have read in everything above a ---- by now
		newtodo = (line + "".join(todo)) # keep the ---- line
		open("todo", "w").write(newtodo)

		os.system("git commit -m \"" + out + "\"")



